### ISSUE TITLE
Erro de falta de pacote openpyxl

### ISSUE THREAD

**Issue by gabrielbdornas** [transparencia-mg/dtamg-docker#6]
```
root@14291a08718f:/dataset# python scripts/main.py upload/letters.xlsx data/letters.csv
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dataset/scripts/main.py", line 11, in <module>
    convert_csv(sys.argv[1], sys.argv[2])
  File "/dataset/scripts/main.py", line 7, in convert_csv
    read_file = pd.read_excel (xlsx_file_path, )
  File "/usr/local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pandas/io/excel/_base.py", line 457, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/usr/local/lib/python3.9/site-packages/pandas/io/excel/_base.py", line 1419, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "/usr/local/lib/python3.9/site-packages/pandas/io/excel/_openpyxl.py", line 524, in __init__
    import_optional_dependency("openpyxl")
  File "/usr/local/lib/python3.9/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
```

**Comment by gabrielbdornas** [comment]
Fixed [here](https://github.com/transparencia-mg/dtamg-docker/blob/6e56892da4837adef9490cce24e747ff7acbf52f/requirements.txt)
